### ISSUE TITLE
failing to install scanCONTROL

### ISSUE THREAD

**Issue by Joeri-Vos** [sam-xl/scancontrol#1]
when trying to install micro epsilon scancontrol it creates the following messages:

Install Micro Epsilon scanCONTROL API (y/n)?y
Architecture: x86_64
ln: failed to create symbolic link '/usr/local/lib/libllt.so': File exists
ln: failed to create symbolic link '/usr/local/lib/libmescan.so': File exists

I tried to catkin_make the workspace anyways, but that resulted in the following error messages:

/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp: In constructor ‘scancontrol_driver::ScanControlDriver::ScanControlDriver(ros::NodeHandle, ros::NodeHandle)’:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:13: error: ‘return_value’ was not declared in this scope
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
             ^~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:13: note: suggested alternative: ‘return_code’
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
             ^~~~~~~~~~~~
             return_code
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:46: error: invalid conversion from ‘int*’ to ‘int’ [-fpermissive]
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
                                              ^~~~~~~~~~~~~~~~~~~
In file included from /home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:1:0:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/include/scancontrol/driver.h:34:17: note:   initializing argument 1 of ‘int scancontrol_driver::ScanControlDriver::SetPartialProfile(int&)’
             int SetPartialProfile(int &resolution);
                 ^~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:46: error: cannot bind rvalue ‘(int)(&((scancontrol_driver::ScanControlDriver*)this)->scancontrol_driver::ScanControlDriver::config_.scancontrol_driver::ScanControlDriver::<unnamed struct>::resolution)’ to ‘int&’
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
                                              ^~~~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp: In member function ‘int scancontrol_driver::ScanControlDriver::SetPartialProfile(int&)’:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:221:14: error: ‘return_value’ was not declared in this scope
         if ((return_value = device_interface.SetProfileConfig(PARTIAL_PROFILE)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:221:14: note: suggested alternative: ‘si_value’
         if ((return_value = device_interface.SetProfileConfig(PARTIAL_PROFILE)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
              si_value
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:233:14: error: ‘return_value’ was not declared in this scope
         if ((return_value = device_interface.SetPartialProfile(&t_partial_profile_)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:233:14: note: suggested alternative: ‘si_value’
         if ((return_value = device_interface.SetPartialProfile(&t_partial_profile_)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
              si_value
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp: In member function ‘bool scancontrol_driver::ScanControlDriver::ServiceSetResolution(scancontrol::SetResolution::Request&, scancontrol::SetResolution::Response&)’:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:380:54: error: invalid conversion from ‘scancontrol::SetResolutionRequest_<std::allocator<void> >::_resolution_type* {aka unsigned int*}’ to ‘int’ [-fpermissive]
         if (response.return_code = SetPartialProfile(&(request.resolution)) < GENERAL_FUNCTION_OK){
                                                      ^~~~~~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:219:9: note:   initializing argument 1 of ‘int scancontrol_driver::ScanControlDriver::SetPartialProfile(int&)’
     int ScanControlDriver::SetPartialProfile(int &resolution){
         ^~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:380:54: error: cannot bind rvalue ‘(int)(& request.scancontrol::SetResolutionRequest_<std::allocator<void> >::resolution)’ to ‘int&’
         if (response.return_code = SetPartialProfile(&(request.resolution)) < GENERAL_FUNCTION_OK){
                                                      ^~~~~~~~~~~~~~~~~~~~~
micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_nodelet.dir/build.make:86: recipe for target 'micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_nodelet.dir/src/driver.cpp.o' failed
make[2]: *** [micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_nodelet.dir/src/driver.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target scancontrol_generate_messages
[ 97%] Built target scancontrol_generate_messages
CMakeFiles/Makefile2:1587: recipe for target 'micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_nodelet.dir/all' failed
make[1]: *** [micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_nodelet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp: In constructor ‘scancontrol_driver::ScanControlDriver::ScanControlDriver(ros::NodeHandle, ros::NodeHandle)’:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:13: error: ‘return_value’ was not declared in this scope
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
             ^~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:13: note: suggested alternative: ‘return_code’
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
             ^~~~~~~~~~~~
             return_code
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:46: error: invalid conversion from ‘int*’ to ‘int’ [-fpermissive]
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
                                              ^~~~~~~~~~~~~~~~~~~
In file included from /home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:1:0:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/include/scancontrol/driver.h:34:17: note:   initializing argument 1 of ‘int scancontrol_driver::ScanControlDriver::SetPartialProfile(int&)’
             int SetPartialProfile(int &resolution);
                 ^~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:185:46: error: cannot bind rvalue ‘(int)(&((scancontrol_driver::ScanControlDriver*)this)->scancontrol_driver::ScanControlDriver::config_.scancontrol_driver::ScanControlDriver::<unnamed struct>::resolution)’ to ‘int&’
         if (return_value = SetPartialProfile(&config_.resolution) < GENERAL_FUNCTION_OK){
                                              ^~~~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp: In member function ‘int scancontrol_driver::ScanControlDriver::SetPartialProfile(int&)’:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:221:14: error: ‘return_value’ was not declared in this scope
         if ((return_value = device_interface.SetProfileConfig(PARTIAL_PROFILE)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:221:14: note: suggested alternative: ‘si_value’
         if ((return_value = device_interface.SetProfileConfig(PARTIAL_PROFILE)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
              si_value
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:233:14: error: ‘return_value’ was not declared in this scope
         if ((return_value = device_interface.SetPartialProfile(&t_partial_profile_)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:233:14: note: suggested alternative: ‘si_value’
         if ((return_value = device_interface.SetPartialProfile(&t_partial_profile_)) < GENERAL_FUNCTION_OK){
              ^~~~~~~~~~~~
              si_value
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp: In member function ‘bool scancontrol_driver::ScanControlDriver::ServiceSetResolution(scancontrol::SetResolution::Request&, scancontrol::SetResolution::Response&)’:
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:380:54: error: invalid conversion from ‘scancontrol::SetResolutionRequest_<std::allocator<void> >::_resolution_type* {aka unsigned int*}’ to ‘int’ [-fpermissive]
         if (response.return_code = SetPartialProfile(&(request.resolution)) < GENERAL_FUNCTION_OK){
                                                      ^~~~~~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:219:9: note:   initializing argument 1 of ‘int scancontrol_driver::ScanControlDriver::SetPartialProfile(int&)’
     int ScanControlDriver::SetPartialProfile(int &resolution){
         ^~~~~~~~~~~~~~~~~
/home/joerivos/Documents/catkin_ws/src/micro_epsilon_scancontrol-develop/scancontrol/src/driver.cpp:380:54: error: cannot bind rvalue ‘(int)(& request.scancontrol::SetResolutionRequest_<std::allocator<void> >::resolution)’ to ‘int&’
         if (response.return_code = SetPartialProfile(&(request.resolution)) < GENERAL_FUNCTION_OK){
                                                      ^~~~~~~~~~~~~~~~~~~~~
micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_node.dir/build.make:86: recipe for target 'micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_node.dir/src/driver.cpp.o' failed
make[2]: *** [micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_node.dir/src/driver.cpp.o] Error 1
CMakeFiles/Makefile2:1624: recipe for target 'micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_node.dir/all' failed
make[1]: *** [micro_epsilon_scancontrol-develop/scancontrol/CMakeFiles/driver_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by dave992** [comment]
The installation script says the files already exist, causing the first error. This means the libraries are already installed. You can check by looking in the /usr/local/lib folder and in /usr/local/include. The install script is only an automated way to copy the library files to the correct location and update the index Linux uses to find these files when compiling. 

The second error using catkin_make is not related to the installation itself, but to building the package. I will have a look at it later as I have to fire up Linux to debug it.

**Comment by dave992** [comment]
I've just pushed the changes that should fix your issues, and I am now able to successfully build the node. As such I am closing this issue.
