### ISSUE TITLE
Scanner type not recognized

### ISSUE THREAD

**Issue by Joeri-Vos** [sam-xl/scancontrol#5]
when i start the rqt plugin for the scanner i get this warning:
[WARN] [1576571708.299480]: Profile settings disabled. Scanner type not recognized.

I need the profile settings to be enabled to invert the z

I am using the scanner of type 2950-25.
when i print self.scanner type it returns 65536

**Comment by dave992** [comment]
I will have a look at it later today and try to pinpoint the issue.

**Comment by dave992** [comment]
The scanner type can actually not be requested using a GetFeature call as is done now by the GUI. I will implement two services to control the inversion of X and Z values which the GUI (and other nodes etc.) can use to enable this functionality.
