### ISSUE TITLE
Investigate automated testing of the driver

### ISSUE THREAD

**Issue by dave992** [sam-xl/scancontrol#9]
Currently, the driver is not tested as new commits and pull requests are issued. 

Any suggestions on how to approach automated testing for a device driver that is not available during these automated tests? E.g. would I need to write a device/API emulator?

**Comment by gavanderhoorn** [comment]
It depends on what you actually want to do.

If you're looking for compile-testing code on every PR, that could be done, but you'd probably have to somehow work around/mock the `libllt` and `libme` dependencies. Seeing as registration is still required to be able to download the Linux SDK, I'm not sure we could package them for easy redistribution (which would be needed for any CI setup).

If you're thinking of how to test the actual driver functionality, you'd need to have either hardware-in-the-loop or a model-in-the-loop. Creating a MiL is not going to be easy. HiL is also not easy in this case, and it would also be limited to local testing, as it's not straightforward to expose actual hw somehow to the CI setup (at least: an off-premise one).

I would go for setting up basic compile-testing CI for now. The challenges are managable, and it would tremendously help in guaranteeing not breaking anything when merging PRs.

**Comment by dave992** [comment]
Thanks for the feedback! I hoped there would have been tools to create the model-in-the-loop, but was already afraid there wasn't (At least were not able to find any). 

I will work on setting up the compile testing CI then, with a workaround for the `libllt` and `libme`.

**Comment by gavanderhoorn** [comment]
> I hoped there would have been tools to create the model-in-the-loop

would you have any ideas on how those would work?

**Comment by dave992** [comment]
> > I hoped there would have been tools to create the model-in-the-loop
> 
> would you have any ideas on how those would work?

A tool that can be attached to a class/function and records the inputs and outputs when used. This could then be used to build a test class that copies the successful run with real hardware by matching the same input and output patterns. Probably not as easy as it sounds and would not fully model the sensor, but its something. 

On another note, the `libme` and `libllt` are licenced under LGPL v3, I've not fully read in on the licence but a quick first search showed that it is not proprietary and could be included with the software or in this case with the CI pipeline. This would make setting up the compile testing way easier.

**Comment by dave992** [comment]
Implemented in #20
